"""SendKit: modular Python SDK for WhatsApp and bulk SMS providers.

Sync and async provider clients for the Meta WhatsApp Cloud API, Onfon bulk SMS,
and Africa's Talking SMS, sharing one configurable httpx-backed transport with
retries, hooks, and per-request options.
"""

from __future__ import annotations

from .core.config import get_env_number, get_optional_env, get_required_env
from .core.errors import (
    ApiError,
    ConfigurationError,
    NetworkError,
    ProviderError,
    SendKitError,
    TimeoutError,
    WebhookVerificationError,
)
from .core.http import AsyncHttpClient, HttpClient
from .core.types import (
    AfterResponseContext,
    BeforeRequestContext,
    ErrorContext,
    Hooks,
    HttpMethod,
    HttpRequestOptions,
    RequestOptions,
    RetryDecisionContext,
    RetryPolicy,
)
from .events import DeliveryEvent, DeliveryState, MessageChannel
from .providers.sms import (
    AFRICASTALKING_SANDBOX_SMS_BASE_URL,
    AFRICASTALKING_SMS_BASE_URL,
    ONFON_BASE_URL,
    ONFON_SMS_BASE_URL,
    AfricasTalkingDeliveryReport,
    AfricasTalkingFetchMessagesRequest,
    AfricasTalkingFetchMessagesResult,
    AfricasTalkingIncomingMessage,
    AfricasTalkingPremiumSmsRequest,
    AfricasTalkingSmsClient,
    AfricasTalkingSubscriptionRequest,
    AfricasTalkingSubscriptionResult,
    AsyncAfricasTalkingSmsClient,
    AsyncOnfonSmsClient,
    OnfonSmsClient,
    SmsBalance,
    SmsBalanceEntry,
    SmsClient,
    SmsGroup,
    SmsGroupUpsertRequest,
    SmsManagementResult,
    SmsMessage,
    SmsSendReceipt,
    SmsSendRequest,
    SmsSendResult,
    SmsSendStatus,
    SmsTemplate,
    SmsTemplateUpsertRequest,
    parse_africastalking_delivery_report,
)
from .providers.whatsapp import (
    META_GRAPH_API_VERSION,
    META_GRAPH_BASE_URL,
    AsyncMetaWhatsAppClient,
    MetaWhatsAppClient,
    WhatsAppCatalogMessageRequest,
    WhatsAppClient,
    WhatsAppContact,
    WhatsAppContactAddress,
    WhatsAppContactEmail,
    WhatsAppContactName,
    WhatsAppContactOrg,
    WhatsAppContactPhone,
    WhatsAppContactsRequest,
    WhatsAppContactUrl,
    WhatsAppFlowActionType,
    WhatsAppFlowMessageRequest,
    WhatsAppInboundLocation,
    WhatsAppInboundMedia,
    WhatsAppInboundMessage,
    WhatsAppInboundReaction,
    WhatsAppInboundReply,
    WhatsAppInteractiveButton,
    WhatsAppInteractiveHeader,
    WhatsAppInteractiveRequest,
    WhatsAppInteractiveRow,
    WhatsAppInteractiveSection,
    WhatsAppLocationRequest,
    WhatsAppManagedTemplate,
    WhatsAppMediaDeleteResult,
    WhatsAppMediaInfo,
    WhatsAppMediaRequest,
    WhatsAppMediaUploadRequest,
    WhatsAppMediaUploadResult,
    WhatsAppProductItem,
    WhatsAppProductListRequest,
    WhatsAppProductMessageRequest,
    WhatsAppProductSection,
    WhatsAppReactionRequest,
    WhatsAppReadRequest,
    WhatsAppSendReceipt,
    WhatsAppSendResult,
    WhatsAppStatusResult,
    WhatsAppTemplateButtonDefinition,
    WhatsAppTemplateComponent,
    WhatsAppTemplateComponentDefinition,
    WhatsAppTemplateCreateRequest,
    WhatsAppTemplateDeleteRequest,
    WhatsAppTemplateDeleteResult,
    WhatsAppTemplateListRequest,
    WhatsAppTemplateListResult,
    WhatsAppTemplateListSummary,
    WhatsAppTemplateMutationResult,
    WhatsAppTemplateParameter,
    WhatsAppTemplateRequest,
    WhatsAppTemplateUpdateRequest,
    WhatsAppTextRequest,
)
from .webhooks import (
    parse_africastalking_sms_delivery_report,
    parse_onfon_delivery_report,
    require_valid_meta_signature,
    resolve_meta_subscription_challenge,
    verify_meta_signature,
)

__all__ = [
    # Base URLs / versions
    "AFRICASTALKING_SANDBOX_SMS_BASE_URL",
    "AFRICASTALKING_SMS_BASE_URL",
    "ONFON_BASE_URL",
    "ONFON_SMS_BASE_URL",
    "META_GRAPH_API_VERSION",
    "META_GRAPH_BASE_URL",
    # Errors
    "SendKitError",
    "ConfigurationError",
    "ApiError",
    "ProviderError",
    "NetworkError",
    "TimeoutError",
    "WebhookVerificationError",
    # Transport
    "HttpClient",
    "AsyncHttpClient",
    "HttpMethod",
    "RequestOptions",
    "HttpRequestOptions",
    "RetryPolicy",
    "RetryDecisionContext",
    "Hooks",
    "BeforeRequestContext",
    "AfterResponseContext",
    "ErrorContext",
    # Env helpers
    "get_optional_env",
    "get_required_env",
    "get_env_number",
    # Events
    "DeliveryEvent",
    "DeliveryState",
    "MessageChannel",
    # SMS clients
    "OnfonSmsClient",
    "AsyncOnfonSmsClient",
    "AfricasTalkingSmsClient",
    "AsyncAfricasTalkingSmsClient",
    # SMS models
    "SmsClient",
    "SmsMessage",
    "SmsSendRequest",
    "SmsSendReceipt",
    "SmsSendResult",
    "SmsSendStatus",
    "SmsBalance",
    "SmsBalanceEntry",
    "SmsGroup",
    "SmsGroupUpsertRequest",
    "SmsTemplate",
    "SmsTemplateUpsertRequest",
    "SmsManagementResult",
    "AfricasTalkingDeliveryReport",
    "AfricasTalkingFetchMessagesRequest",
    "AfricasTalkingFetchMessagesResult",
    "AfricasTalkingIncomingMessage",
    "AfricasTalkingPremiumSmsRequest",
    "AfricasTalkingSubscriptionRequest",
    "AfricasTalkingSubscriptionResult",
    "parse_africastalking_delivery_report",
    # WhatsApp clients
    "MetaWhatsAppClient",
    "AsyncMetaWhatsAppClient",
    # WhatsApp models
    "WhatsAppClient",
    "WhatsAppTextRequest",
    "WhatsAppTemplateRequest",
    "WhatsAppTemplateComponent",
    "WhatsAppTemplateParameter",
    "WhatsAppTemplateButtonDefinition",
    "WhatsAppTemplateComponentDefinition",
    "WhatsAppTemplateListRequest",
    "WhatsAppTemplateListResult",
    "WhatsAppTemplateListSummary",
    "WhatsAppTemplateCreateRequest",
    "WhatsAppTemplateUpdateRequest",
    "WhatsAppTemplateDeleteRequest",
    "WhatsAppTemplateDeleteResult",
    "WhatsAppTemplateMutationResult",
    "WhatsAppManagedTemplate",
    "WhatsAppMediaRequest",
    "WhatsAppMediaUploadRequest",
    "WhatsAppMediaUploadResult",
    "WhatsAppMediaInfo",
    "WhatsAppMediaDeleteResult",
    "WhatsAppLocationRequest",
    "WhatsAppContactsRequest",
    "WhatsAppContact",
    "WhatsAppContactName",
    "WhatsAppContactPhone",
    "WhatsAppContactEmail",
    "WhatsAppContactUrl",
    "WhatsAppContactAddress",
    "WhatsAppContactOrg",
    "WhatsAppReactionRequest",
    "WhatsAppInteractiveRequest",
    "WhatsAppInteractiveHeader",
    "WhatsAppInteractiveButton",
    "WhatsAppInteractiveSection",
    "WhatsAppInteractiveRow",
    "WhatsAppCatalogMessageRequest",
    "WhatsAppProductMessageRequest",
    "WhatsAppProductListRequest",
    "WhatsAppProductSection",
    "WhatsAppProductItem",
    "WhatsAppFlowMessageRequest",
    "WhatsAppFlowActionType",
    "WhatsAppReadRequest",
    "WhatsAppStatusResult",
    "WhatsAppSendReceipt",
    "WhatsAppSendResult",
    "WhatsAppInboundMessage",
    "WhatsAppInboundMedia",
    "WhatsAppInboundLocation",
    "WhatsAppInboundReply",
    "WhatsAppInboundReaction",
    # Webhooks
    "resolve_meta_subscription_challenge",
    "verify_meta_signature",
    "require_valid_meta_signature",
    "parse_onfon_delivery_report",
    "parse_africastalking_sms_delivery_report",
]
