"""Tests for the filesystem convenience helpers."""

from __future__ import annotations

import base64
from pathlib import Path

from sendstack import (
    attachment_from_bytes,
    attachment_from_file,
    html_from_file,
    text_from_file,
)


def test_html_from_file_reads_utf8(tmp_path: Path) -> None:
    path = tmp_path / "welcome.html"
    path.write_text("<p>Hëllo</p>", encoding="utf-8")

    assert html_from_file(path) == "<p>Hëllo</p>"


def test_text_from_file_reads_utf8_and_honors_encoding(tmp_path: Path) -> None:
    path = tmp_path / "welcome.txt"
    path.write_text("Héllo", encoding="latin-1")

    assert text_from_file(path, encoding="latin-1") == "Héllo"


def test_attachment_from_file_defaults_filename_to_basename(tmp_path: Path) -> None:
    path = tmp_path / "invoice.pdf"
    payload = b"%PDF-1.4 fake"
    path.write_bytes(payload)

    assert attachment_from_file(path) == {
        "filename": "invoice.pdf",
        "content_base64": base64.b64encode(payload).decode("ascii"),
    }


def test_attachment_from_file_accepts_str_path_and_overrides(tmp_path: Path) -> None:
    path = tmp_path / "logo.png"
    payload = bytes([0x89, 0x50, 0x4E, 0x47])
    path.write_bytes(payload)

    # Pass the path as a str to exercise the os.fspath branch.
    assert attachment_from_file(
        str(path),
        filename="brand-logo.png",
        content_type="image/png",
        inline=True,
        content_id="logo",
    ) == {
        "filename": "brand-logo.png",
        "content_base64": base64.b64encode(payload).decode("ascii"),
        "content_type": "image/png",
        "inline": True,
        "content_id": "logo",
    }


def test_attachment_from_bytes_minimal() -> None:
    data = b"generated bytes"

    assert attachment_from_bytes(data, filename="report.bin") == {
        "filename": "report.bin",
        "content_base64": base64.b64encode(data).decode("ascii"),
    }


def test_attachment_from_bytes_with_all_metadata() -> None:
    data = bytes([1, 2, 3, 4])

    assert attachment_from_bytes(
        data,
        filename="raw.dat",
        content_type="application/octet-stream",
        inline=False,
        content_id="raw",
    ) == {
        "filename": "raw.dat",
        "content_base64": base64.b64encode(data).decode("ascii"),
        "content_type": "application/octet-stream",
        "inline": False,
        "content_id": "raw",
    }
