"""Official Python SDK for the SendStack email SaaS API.

Sync (:class:`Sendstack`) and async (:class:`AsyncSendstack`) clients covering
the SendStack developer API: transactional and scheduled email, batch email,
reusable attachment uploads, sending domains, email templates, webhook endpoints
and event retries, and suppression lists.
"""

from __future__ import annotations

from .client import (
    AsyncSendstack,
    AsyncSendstackClient,
    Sendstack,
    SendstackClient,
)
from .errors import (
    SendstackError,
    is_error_envelope,
    is_success_envelope,
    to_sendstack_error,
)
from .types import (
    DEFAULT_BASE_URL,
    BearerAuthStrategy,
    CreateDomainRequest,
    CreateSuppressionRequest,
    CreateSuppressionResult,
    CreateTemplateRequest,
    CreateWebhookEndpointRequest,
    CursorPage,
    Domain,
    DomainCapabilities,
    DomainCapability,
    DomainRegion,
    DomainTlsPolicy,
    EmailEvent,
    EmailMessage,
    EmailStatus,
    EmailTemplate,
    HeadersAuthStrategy,
    KnownWebhookEvent,
    Recipient,
    RequestOptions,
    ResponseParser,
    ResponseTransformer,
    RetryOptions,
    SendEmailBatchResult,
    SendEmailRequest,
    SendEmailResult,
    SendstackAuthStrategy,
    SendstackMiddleware,
    SendstackRequestContext,
    SendstackResponseContext,
    SendstackRetryContext,
    SendstackTag,
    Suppression,
    SuppressionReason,
    TemplateReference,
    UpdateTemplateRequest,
    UpdateWebhookEndpointRequest,
    UploadAttachmentRequest,
    UploadedAttachment,
    WebhookEndpoint,
    WebhookEventType,
)

__all__ = [
    "DEFAULT_BASE_URL",
    # Clients
    "Sendstack",
    "AsyncSendstack",
    "SendstackClient",
    "AsyncSendstackClient",
    # Errors
    "SendstackError",
    "is_error_envelope",
    "is_success_envelope",
    "to_sendstack_error",
    # Auth
    "BearerAuthStrategy",
    "HeadersAuthStrategy",
    "SendstackAuthStrategy",
    # Options + machinery
    "RequestOptions",
    "RetryOptions",
    "SendstackMiddleware",
    "SendstackRequestContext",
    "SendstackResponseContext",
    "SendstackRetryContext",
    "ResponseParser",
    "ResponseTransformer",
    # API models
    "Recipient",
    "SendstackTag",
    "TemplateReference",
    "SendEmailRequest",
    "SendEmailResult",
    "SendEmailBatchResult",
    "EmailMessage",
    "EmailEvent",
    "EmailStatus",
    "UploadAttachmentRequest",
    "UploadedAttachment",
    "CreateDomainRequest",
    "DomainCapabilities",
    "DomainCapability",
    "DomainRegion",
    "DomainTlsPolicy",
    "Domain",
    "CreateTemplateRequest",
    "UpdateTemplateRequest",
    "EmailTemplate",
    "CreateWebhookEndpointRequest",
    "UpdateWebhookEndpointRequest",
    "WebhookEndpoint",
    "WebhookEventType",
    "KnownWebhookEvent",
    "CreateSuppressionRequest",
    "CreateSuppressionResult",
    "Suppression",
    "SuppressionReason",
    "CursorPage",
]
