"""Official Python SDK for the SendStack email SaaS API.

Sync (:class:`Sendstack`) and async (:class:`AsyncSendstack`) clients covering
the SendStack developer API: transactional and scheduled email, SMS and
WhatsApp, batch sends, reusable attachment uploads, sending domains, WhatsApp
senders, email/SMS/WhatsApp templates, webhook endpoints and event retries, and
suppression lists.
"""

from __future__ import annotations

from .client import (
    AsyncSendstack,
    AsyncSendstackClient,
    Sendstack,
    SendstackClient,
)
from .errors import (
    SendstackError,
    is_error_envelope,
    is_success_envelope,
    to_sendstack_error,
)
from .files import (
    attachment_from_bytes,
    attachment_from_file,
    html_from_file,
    text_from_file,
)
from .types import (
    DEFAULT_BASE_URL,
    BearerAuthStrategy,
    BillingProduct,
    CheckoutRequest,
    CheckoutResult,
    CreateDomainRequest,
    CreateSenderIdRequest,
    CreateSuppressionRequest,
    CreateSuppressionResult,
    CreateTemplateRequest,
    CreateWebhookEndpointRequest,
    CreateWhatsAppSenderRequest,
    CreditBalance,
    CreditChannel,
    CursorPage,
    Domain,
    DomainCapabilities,
    DomainCapability,
    DomainRegion,
    DomainTlsPolicy,
    EmailDefaults,
    EmailEvent,
    EmailMessage,
    EmailStatus,
    EmailTemplate,
    HeadersAuthStrategy,
    KnownWebhookEvent,
    Payment,
    PaySenderIdRequest,
    PaySenderIdResult,
    PreviewTemplateRequest,
    Purchase,
    Recipient,
    RequestOptions,
    ResponseParser,
    ResponseTransformer,
    RetryOptions,
    SendEmailBatchResult,
    SendEmailRequest,
    SendEmailResult,
    SenderAuthLetter,
    SenderEntityType,
    SenderIdNetwork,
    SenderIdNetworkState,
    SenderIdOptions,
    SenderIdRequest,
    SenderIdRequestRef,
    SenderKycDocument,
    SendSmsBatchResult,
    SendSmsRequest,
    SendSmsResult,
    SendstackAuthStrategy,
    SendstackList,
    SendstackMiddleware,
    SendstackRequestContext,
    SendstackResponseContext,
    SendstackRetryContext,
    SendstackTag,
    SendWhatsAppBatchResult,
    SendWhatsAppRequest,
    SendWhatsAppResult,
    SmsDefaults,
    SmsEvent,
    SmsMessage,
    SmsStatus,
    Suppression,
    SuppressionReason,
    TemplateChannel,
    TemplatePreview,
    TemplateVariable,
    UpdateTemplateRequest,
    UpdateWebhookEndpointRequest,
    UploadAttachmentRequest,
    UploadedAttachment,
    UploadSenderKycRequest,
    WebhookEndpoint,
    WebhookEventType,
    WhatsAppDefaults,
    WhatsAppEvent,
    WhatsAppMediaRef,
    WhatsAppMessage,
    WhatsAppSender,
    WhatsAppSenderRef,
    WhatsAppStatus,
    WhatsAppTemplateCategory,
    WhatsAppTemplateRef,
)

__all__ = [
    "DEFAULT_BASE_URL",
    # Clients
    "Sendstack",
    "AsyncSendstack",
    "SendstackClient",
    "AsyncSendstackClient",
    # Errors
    "SendstackError",
    "is_error_envelope",
    "is_success_envelope",
    "to_sendstack_error",
    # Filesystem helpers
    "html_from_file",
    "text_from_file",
    "attachment_from_file",
    "attachment_from_bytes",
    # Auth
    "BearerAuthStrategy",
    "HeadersAuthStrategy",
    "SendstackAuthStrategy",
    # Options + machinery
    "RequestOptions",
    "RetryOptions",
    "SendstackMiddleware",
    "SendstackRequestContext",
    "SendstackResponseContext",
    "SendstackRetryContext",
    "ResponseParser",
    "ResponseTransformer",
    # API models
    "Recipient",
    "SendstackTag",
    "SendEmailRequest",
    "SendEmailResult",
    "SendEmailBatchResult",
    "EmailMessage",
    "EmailEvent",
    "EmailStatus",
    "SendSmsRequest",
    "SendSmsResult",
    "SendSmsBatchResult",
    "SmsMessage",
    "SmsEvent",
    "SmsStatus",
    "SendWhatsAppRequest",
    "SendWhatsAppResult",
    "SendWhatsAppBatchResult",
    "WhatsAppMessage",
    "WhatsAppEvent",
    "WhatsAppStatus",
    "WhatsAppTemplateRef",
    "WhatsAppTemplateCategory",
    "WhatsAppMediaRef",
    "CreateWhatsAppSenderRequest",
    "WhatsAppSender",
    "WhatsAppSenderRef",
    "EmailDefaults",
    "SmsDefaults",
    "WhatsAppDefaults",
    "UploadAttachmentRequest",
    "UploadedAttachment",
    "CreateDomainRequest",
    "DomainCapabilities",
    "DomainCapability",
    "DomainRegion",
    "DomainTlsPolicy",
    "Domain",
    "CreateTemplateRequest",
    "UpdateTemplateRequest",
    "TemplateChannel",
    "TemplateVariable",
    "PreviewTemplateRequest",
    "TemplatePreview",
    "EmailTemplate",
    "CreateWebhookEndpointRequest",
    "UpdateWebhookEndpointRequest",
    "WebhookEndpoint",
    "WebhookEventType",
    "KnownWebhookEvent",
    "CreateSuppressionRequest",
    "CreateSuppressionResult",
    "Suppression",
    "SuppressionReason",
    "CursorPage",
    "SendstackList",
    # SMS sender-ID provisioning
    "CreateSenderIdRequest",
    "SenderKycDocument",
    "SenderAuthLetter",
    "UploadSenderKycRequest",
    "PaySenderIdRequest",
    "PaySenderIdResult",
    "SenderIdRequest",
    "SenderIdRequestRef",
    "SenderIdNetworkState",
    "SenderIdOptions",
    "SenderIdNetwork",
    "SenderEntityType",
    # Billing
    "CreditBalance",
    "CreditChannel",
    "BillingProduct",
    "CheckoutRequest",
    "CheckoutResult",
    "Payment",
    "Purchase",
]
