"""SMS provider clients and shared SMS models."""

from __future__ import annotations

from .africastalking import (
    AFRICASTALKING_SANDBOX_SMS_BASE_URL,
    AFRICASTALKING_SMS_BASE_URL,
    AfricasTalkingSmsClient,
    AsyncAfricasTalkingSmsClient,
    parse_africastalking_delivery_report,
)
from .client import (
    ONFON_BASE_URL,
    ONFON_SMS_BASE_URL,
    AsyncOnfonSmsClient,
    OnfonSmsClient,
)
from .types import (
    AfricasTalkingDeliveryReport,
    AfricasTalkingFetchMessagesRequest,
    AfricasTalkingFetchMessagesResult,
    AfricasTalkingIncomingMessage,
    AfricasTalkingPremiumSmsRequest,
    AfricasTalkingSubscriptionRequest,
    AfricasTalkingSubscriptionResult,
    SmsBalance,
    SmsBalanceEntry,
    SmsClient,
    SmsGroup,
    SmsGroupUpsertRequest,
    SmsManagementResult,
    SmsMessage,
    SmsSendReceipt,
    SmsSendRequest,
    SmsSendResult,
    SmsSendStatus,
    SmsTemplate,
    SmsTemplateUpsertRequest,
)

__all__ = [
    "AFRICASTALKING_SANDBOX_SMS_BASE_URL",
    "AFRICASTALKING_SMS_BASE_URL",
    "ONFON_BASE_URL",
    "ONFON_SMS_BASE_URL",
    "AfricasTalkingDeliveryReport",
    "AfricasTalkingFetchMessagesRequest",
    "AfricasTalkingFetchMessagesResult",
    "AfricasTalkingIncomingMessage",
    "AfricasTalkingPremiumSmsRequest",
    "AfricasTalkingSmsClient",
    "AfricasTalkingSubscriptionRequest",
    "AfricasTalkingSubscriptionResult",
    "AsyncAfricasTalkingSmsClient",
    "AsyncOnfonSmsClient",
    "OnfonSmsClient",
    "SmsBalance",
    "SmsBalanceEntry",
    "SmsClient",
    "SmsGroup",
    "SmsGroupUpsertRequest",
    "SmsManagementResult",
    "SmsMessage",
    "SmsSendReceipt",
    "SmsSendRequest",
    "SmsSendResult",
    "SmsSendStatus",
    "SmsTemplate",
    "SmsTemplateUpsertRequest",
    "parse_africastalking_delivery_report",
]
